mongodbDocker:
  image: mongo

redisDocker:
  image: redis

microserviceone:
  build: ./MicroServiceOne
  environment:
    - PORT=10010
    - mongoUri=mongodb://mongodbDocker/app-dev
    - redisDocker=redisDocker
    - mongodbDocker=mongodbDocker
  ports:
    - "8000:10010"
  links:
    - mongodbDocker
    - redisDocker
